# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(938, 557)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("YouTubeIco.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.subtitle_box = QtWidgets.QGroupBox(self.centralwidget)
        self.subtitle_box.setGeometry(QtCore.QRect(10, 70, 921, 481))
        self.subtitle_box.setObjectName("subtitle_box")
        self.layoutWidget = QtWidgets.QWidget(self.subtitle_box)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 30, 160, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.column_check = QtWidgets.QCheckBox(self.layoutWidget)
        self.column_check.setEnabled(False)
        self.column_check.setObjectName("column_check")
        self.verticalLayout.addWidget(self.column_check)
        self.pick_language_box = QtWidgets.QComboBox(self.layoutWidget)
        self.pick_language_box.setEnabled(False)
        self.pick_language_box.setEditable(False)
        self.pick_language_box.setCurrentText("")
        self.pick_language_box.setObjectName("pick_language_box")
        self.verticalLayout.addWidget(self.pick_language_box)
        self.show_subtitles_button = QtWidgets.QPushButton(self.layoutWidget)
        self.show_subtitles_button.setEnabled(False)
        self.show_subtitles_button.setObjectName("show_subtitles_button")
        self.verticalLayout.addWidget(self.show_subtitles_button)
        self.download_subtitles_button = QtWidgets.QPushButton(self.layoutWidget)
        self.download_subtitles_button.setEnabled(False)
        self.download_subtitles_button.setObjectName("download_subtitles_button")
        self.verticalLayout.addWidget(self.download_subtitles_button)
        self.subtitles_area = QtWidgets.QTextEdit(self.subtitle_box)
        self.subtitles_area.setGeometry(QtCore.QRect(10, 30, 731, 441))
        self.subtitles_area.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.subtitles_area.setStyleSheet("border: 2px solid #f66867;\n"
"border-color: rgb(218, 0, 0);")
        self.subtitles_area.setLineWidth(0)
        self.subtitles_area.setReadOnly(True)
        self.subtitles_area.setObjectName("subtitles_area")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 921, 51))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 901, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.link_line = QtWidgets.QLineEdit(self.layoutWidget1)
        self.link_line.setStyleSheet("border: 1px solid #f66867;\n"
"border-color: rgb(218, 0, 0);")
        self.link_line.setText("")
        self.link_line.setObjectName("link_line")
        self.horizontalLayout.addWidget(self.link_line)
        self.find_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.find_button.setObjectName("find_button")
        self.horizontalLayout.addWidget(self.find_button)
        self.quality_box = QtWidgets.QComboBox(self.layoutWidget1)
        self.quality_box.setEnabled(False)
        self.quality_box.setObjectName("quality_box")
        self.horizontalLayout.addWidget(self.quality_box)
        self.download_mp4_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.download_mp4_button.setEnabled(False)
        self.download_mp4_button.setObjectName("download_mp4_button")
        self.horizontalLayout.addWidget(self.download_mp4_button)
        self.only_audio_check = QtWidgets.QCheckBox(self.layoutWidget1)
        self.only_audio_check.setObjectName("only_audio_check")
        self.horizontalLayout.addWidget(self.only_audio_check)
        self.only_video_check = QtWidgets.QCheckBox(self.layoutWidget1)
        self.only_video_check.setObjectName("only_video_check")
        self.horizontalLayout.addWidget(self.only_video_check)
        self.cancel_video_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.cancel_video_button.setEnabled(True)
        self.cancel_video_button.setObjectName("cancel_video_button")
        self.horizontalLayout.addWidget(self.cancel_video_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YoutubeParser"))
        self.subtitle_box.setTitle(_translate("MainWindow", "Subtitles"))
        self.label.setText(_translate("MainWindow", "Choose language:"))
        self.column_check.setText(_translate("MainWindow", "Show subtitles as column"))
        self.show_subtitles_button.setText(_translate("MainWindow", "Show subtitles"))
        self.download_subtitles_button.setText(_translate("MainWindow", "Download subtitles"))
        self.groupBox.setTitle(_translate("MainWindow", "Searching for video"))
        self.link_line.setPlaceholderText(_translate("MainWindow", "Input URL of the video here and press find"))
        self.find_button.setText(_translate("MainWindow", "Find"))
        self.download_mp4_button.setText(_translate("MainWindow", "Download"))
        self.only_audio_check.setText(_translate("MainWindow", "Only audio"))
        self.only_video_check.setText(_translate("MainWindow", "Only video"))
        self.cancel_video_button.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
